# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	arc-icon-theme
PORTVERSION=	20161122
PORTEPOCH=	0
CATEGORIES=	x11-themes

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	Arc icon theme

LICENSE=	GPLv3

USE_GITHUB=	yes
GH_ACCOUNT=	horst3180

USES=		autoreconf
GNU_CONFIGURE=	yes
INSTALLS_ICONS=	yes

.include <bsd.port.mk>
