# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	youtube_dl
PORTVERSION=	2017.7.9
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	YouTube video downloader (Python library)

LICENSE=	UNLICENSE

USES=		python
USE_PYTHON=	distutils
NO_ARCH=	yes

.include <bsd.port.mk>
