# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	youtube_dl
PORTVERSION=	2016.10.21.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	YouTube video downloader (Python library)

LICENSE=	UNLICENSE
LICENSE_NAME=	The Unlicense
LICENSE_TEXT=	http://unlicense.org/
LICENSE_PERMS=	dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

USES=		python
USE_PYTHON=	distutils
NO_ARCH=	yes

.include <bsd.port.mk>
