# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	pycryptodomex
PORTVERSION=	3.6.1
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	pycryptodomex-${PORTVERSION}

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	Self-contained cryptographic library for Python

LICENSE=	BSD2CLAUSE PD
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE.rst

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
