# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	demandimport
PORTVERSION=	0.3.3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	On-demand imports, taken from Mercurial

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
