# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	tarjan
PORTVERSION=	0.2.3.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	Python implementation of Tarjan's algorithm

LICENSE=	GPLv3

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
