PORTNAME=	serie
DISTVERSIONPREFIX=	v
DISTVERSION=	0.4.5
CATEGORIES=	devel

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	Rich Git commit graph in your terminal
WWW=		https://github.com/lusingander/serie

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	git:devel/git

USES=		cargo
USE_GITHUB=	yes
GH_ACCOUNT=	lusingander

PLIST_FILES=	bin/serie

.include <bsd.port.mk>
