# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	mini_amf
PORTVERSION=	0.9.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Mini-AMF-${PORTVERSION}

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	Minimal AMF encoder and decoder for Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
