# $FreeBSD$

# vim: ts=8 noet

PORTNAME=	pykka
PORTVERSION=	1.2.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pykka-${PORTVERSION}

MAINTAINER=	petteri.valkonen@iki.fi
COMMENT=	Python implementation of the actor model

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
